updatecli_matrix_version: current
updatecli_amps_release_branch: "release/25.3"
ansible_version_file: vars/acs25.yml
artifacts:
  alfresco-googledrive-repo-community:
    updatecli_scm_id: acsComRepo
    updatecli_xml_target: "/project/properties/alfresco.googledrive.version"
    artifact_version_key: "$.acs_play_community_repository_amp_googledrive_repo_version"
  alfresco-repository-community:
    artifact_name_file: playbooks/group_vars/all.yml
    artifact_name_key: $.acs_play_community_repository_acs_artifact_name
    artifact_version_key: $.acs_play_community_repository_acs_version
    updatecli_matrix_component_key: acs
