galaxy_info:
  author: Lucian Suciu
  description: Tomcat Setup
  company: Alfresco
  min_ansible_version: 2.9
  license: Alfresco
  platforms:
  - name: Centos
    versions:
    - 7
  galaxy_tags: []
allow_duplicates: false
dependencies:
- java
