galaxy_info:
  author: Andrei Ciubotaru
  description: OpenJDK Setup
  company: Alfresco
  min_ansible_version: 2.9
  license: Alfresco
  platforms:
  - name: Centos
    versions:
    - 7
  galaxy_tags: []
dependencies: []
