---
galaxy_info:
  author: Andrei Ciubotaru
  description: Deploys Transform Services
  company: Alfresco
  license: Alfresco
  platforms:
    - name: Centos
      versions:
        - 7
  min_ansible_version: 2.9
  galaxy_tags: []

allow_duplicates: false
dependencies:
  - java
