title: Alfresco Ansible Deployment
description: Deploy Alfresco with Ansible
theme: just-the-docs
color_scheme: alfresco

url: https://alfresco.github.io

aux_links:
  Docs: https://docs.alfresco.com/
  GitHub Repository: https://github.com/Alfresco/alfresco-ansible-deployment

aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: "Improve this page on GitHub"
gh_edit_repository: https://github.com/Alfresco/alfresco-ansible-deployment
gh_edit_branch: master
gh_edit_source: docs
gh_edit_view_mode: edit

logo: "resources/hyland-alfresco-logos.png"
favicon_ico: "favicon.ico"

defaults:
  # apply the default layout to all markdown pages in the docs root folder
  - scope:
      path: "*.md"
    values:
      layout: "default"
      render_with_liquid: false

plugins:
  - jekyll-relative-links
