---
imagemagick_pkg:
  version: 7.0.10-11
  pkgs:
    - imagemagick-distribution-libs-linux
    - imagemagick-distribution-linux

libreoffice: 6.3.5.2
pdf_renderer: 1.1
imagemagick_home: "/usr/lib64/ImageMagick-{{ imagemagick_pkg.version.split('-')[0] }}"
