---
imagemagick_packages:
  - imagemagick-distribution-linux

imagemagick_home: "/opt/imagemagick-{{ imagemagick_version | regex_search('^[0-9]+') }}"

utils_transform:
  - libcairo2
  - libcups2
  - libsm6
  - fontconfig
  - fonts-dejavu
  - libfreetype6
  - libx11-xcb1
